openapi: 3.0.2
info:
  title: IRIS service
  version: '3.0'
  description: Incident service
  contact:
    email: support@alertlogic.com
    name: Alert Logic support
servers:
  - url: 'https://api.cloudinsight.alertlogic.com'
    description: production
    x-alertlogic-session-endpoint: true
  - url: 'https://api.product.dev.alertlogic.com'
    description: integration
    x-alertlogic-session-endpoint: true
paths:
  '/iris/v3/{account_id}/{incident_id}':
    get:
      summary: Get incident
      tags:
        - Incident operations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Incident'
              examples:
                Get Incident response example:
                  value:
                    accountId: number
                    all_assets:
                      - object
                    asset_deployment_type: string
                    asset_host_name: string
                    asset_native_account_id: string
                    assets:
                      __asset: object
                      __contentType: string
                      __messageId: string
                      __normalizedTime: string
                      __relatedOrAssociated: string
                      __source: string
                      __uuid: string
                      al__deployment: string
                      al__subnet: string
                      al__vpc: string
                    attacker:
                      ip: string
                    attacker_lset:
                      - object
                    createTime: number
                    createtimeStr: string
                    customer: string
                    customer_status:
                      status: string
                      status_change_time: string
                    defaultThreatRating: string
                    has_assets: boolean
                    humanFriendlyId: string
                    incident:
                      attackClassId: number
                      attackClassId_str: string
                      subType: string
                      summary: string
                      threatRating: string
                      type: string
                    incidentId: string
                    incident_attack_class: string
                    incident_escalated: string
                    incident_sub_type: string
                    iris_incident_version: number
                    iris_notifications: boolean
                    snooze_status:
                      period_ms: number
                      reason_code: string
                      snoozed: boolean
                    sources:
                      - string
                    updateTime: number
                    updatetime_str: string
                    victim:
                      ip: string
                    victim_lset:
                      - object
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: account_id incident_id combination not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Http 404 example:
                  value:
                    error: "Not found"
                    code: 404
      operationId: get_incident
      description: Get incident
      security:
        - X-AIMS-Auth-Token: []
      x-code-samples:
        - lang: Request Sample
          source: |
            curl -X GET "https://api.cloudinsight.alerlogic.com/iris/v3/12345678/e12345678"
      parameters:
        - schema:
            type: string
          name: account_id
          in: path
          required: true
          description: AIMS Account ID
        - schema:
            $ref: '#/components/schemas/IncidentId'
          name: incident_id
          in: path
          required: true
        - schema:
            type: string
          name: return_value
          in: query
          description: Comma delimited list of dot-notation string names of desired properties in the result set. Use if you want a subset of attributes from the incident
  '/iris/v3/{account_id}/friendly/{friendly_id}':
    get:
      summary: Get incident ID by friendly ID
      tags:
        - Incident operations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FriendlyResponse'
              examples:
                Friendly response example:
                  value:
                    - accountId: number
                      humanFriendlyId: string
                      incidentId: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: account_id friendly_id combination not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Http 404 example:
                  value:
                    error: "Id not found"
                    code: 404
      operationId: get_incident_id_by_friendly
      description: Get incident ID by friendly ID
      security:
        - X-AIMS-Auth-Token: []
      x-code-samples:
        - lang: Request Sample
          source: |
            curl -X GET "https://api.cloudinsight.alerlogic.com/iris/v3/12345678/friendly/k9abcd"
      parameters:
        - schema:
            type: string
          name: account_id
          in: path
          required: true
          description: AIMS Account ID
        - schema:
            type: string
          name: friendly_id
          in: path
          required: true
          description: Human friendly ID. A length 6 alpha-numeric ID shorter than IncidentID
  '/iris/v3/{account_id}/{incident_id}/elaborations/associated':
    get:
      summary: Get associated logs/events for incident
      tags:
        - Incident operations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AssociatedElaborations'
              examples:
                Get associated logs/events response example:
                  value:
                    filter:
                      eq:
                        property: string
                        value: string
                    returnVals:
                      - __appliance_name: string
                        __content_type: string
                        __datacenter: string
                        __hostUUID: string
                        __host_id: string
                        __host_name: string
                        __irisType: string
                        __messageId: string
                        __normalizedTime: string
                        __relatedOrAssociated: string
                        __source: string
                        __sourceName: string
                        __sourceType: string
                        __source_host_ip: string
                        __uuid: string
                        facility: string
                        header: string
                        host_name: string
                        id: object
                        ingest_id: string
                        ingest_ts: number
                        message: string
                        metadata: object
                        priority: number
                        source_id: string
                        time_recv: number
                    stats:
                      matchCounts: array
                      numItemsInDataSource: number
                      numberOfMatchingElaborations: number
                      queryExecutionTime:
                        Aggregation: string
                        Filter: string
                        Hydration: string
                        Match Counts: string
                        Results: string
                        TimeSlice: string
                        Total Query: string
        '400':
          description: Bad request
        '401':
          description: Unauthorized
        '404':
          description: account_id incident_id combination not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Http 404 example:
                  value:
                    error: "Not found"
                    code: 404
      operationId: get_associated_elaborations
      description: Get associated logs/events for incident
      security:
        - X-AIMS-Auth-Token: []
      x-code-samples:
        - lang: Request Sample
          source: |
            curl -X GET "https://api.cloudinsight.alerlogic.com/iris/v3/12345678/e12345678/elaborations/associated"
      parameters:
        - schema:
            type: string
          name: account_id
          in: path
          required: true
          description: AIMS Account ID
        - schema:
            $ref: '#/components/schemas/IncidentId'
          name: incident_id
          in: path
          required: true
        - schema:
            type: string
          name: returnSource
          in: query
          description: 'To filter by source type. Allowed values - log, event'
        - schema:
            type: string
          name: return_value
          in: query
          description: "Comma delimited list of 'dot-notation' string names of desired properties in the result set. Use if you want only a subset of attributes from results"
  '/iris/v3/{account_id}/incidents_by_time':
    get:
      summary: Get incidents in a timespan for account
      tags:
        - Incident operations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IncidentsByTime'
              examples:
                Incidents by time response example:
                  value:
                    - accountId: number
                      all_assets:
                        - object
                      asset_deployment_type: string
                      asset_host_name: string
                      asset_native_account_id: string
                      assets:
                        __asset: object
                        __contentType: string
                        __messageId: string
                        __normalizedTime: string
                        __relatedOrAssociated: string
                        __source: string
                        __uuid: string
                        al__deployment: string
                        al__subnet: string
                        al__vpc: string
                      attacker:
                        ip: string
                      attacker_lset:
                        - object
                      createTime: number
                      createtimeStr: string
                      customer: string
                      customer_status:
                        status: string
                        status_change_time: string
                      defaultThreatRating: string
                      has_assets: boolean
                      humanFriendlyId: string
                      incident:
                        attackClassId: number
                        attackClassId_str: string
                        subType: string
                        summary: string
                        threatRating: string
                        type: string
                      incidentId: string
                      incident_attack_class: string
                      incident_escalated: string
                      incident_sub_type: string
                      iris_incident_version: number
                      iris_notifications: boolean
                      snooze_status:
                        period_ms: number
                        reason_code: string
                        snoozed: boolean
                      sources:
                        - string
                      updateTime: number
                      updatetime_str: string
                      victim:
                        ip: string
                      victim_lset:
                        - object
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Missing start/end time:
                  value:
                    code: 400
                    error: start_time and end_time query strings must be provided
                Invalid arguments:
                  value:
                    code: 400
                    error: Invalid arguments
        '401':
          description: Not authorized
        '403':
          description: Forbidden
      operationId: incidents_by_time
      description: Get incidents in a timespan for an account
      security:
        - X-AIMS-Auth-Token: []
      x-code-samples:
        - lang: Request Sample
          source: |
            curl -X GET "https://api.cloudinsight.alerlogic.com/iris/v3/12345678/incidents_by_time?start_time=1577836800&end_time=1577923200"
      parameters:
        - schema:
            type: string
          name: account_id
          in: path
          required: true
          description: AIMS Account ID
        - schema:
            type: string
          name: start_time
          in: query
          required: true
          description: 'Time to begin span, either epoch timestamp or an ISO string'
        - schema:
            type: string
          name: end_time
          in: query
          required: true
          description: 'Time to end span, either epoch timestamp or an ISO string'
        - schema:
            type: string
          name: return_value
          in: query
          description: Comma delimited list of dot-notation string names of desired properties in the result set. Use if you only want a subset of attributes from each incident
  '/iris/v3/{account_id}/{incident_id}/complete':
    post:
      summary: Complete / close an incident
      tags:
        - UI operations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CompleteIncident'
              examples:
                Complete incident response example:
                  value:
                    new: 
                      notes: This incident is closed because of x
                      reason_code: further_action
                      status: completed
                      status_change_time: 2020-05-22T11:09:56.855569+00:00
                    old:
                      status: open
                      status_change_time: 2020-05-22T07:54:33.555371+00:00
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Invalid account/incident id:
                  value:
                    error: Invalid AccountId or IncidentId supplied
                    code: 400
                Invalid body:
                  value:
                    error: Request body should be valid JSON
                    code: 400
                Invalid arguments:
                  value:
                    error: Invalid arguments
                    code: 400
                Incident already closed:
                  value:
                    error: Incident 12341ab29e36-394e-11e9-a004-720004270420 status is currently the same closed
                    code: 400
        '401':
          description: Not authorized
        '404':
          description: account_id incident_id combination not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Http 404 example:
                  value:
                    error: "Not found"
                    code: 404
        '500':
          description: Internal Server Error 
      operationId: complete_incident
      description: Complete/Close an incident
      security:
        - X-AIMS-Auth-Token: []
      x-code-samples:
        - lang: Request Sample
          source: |
            curl -H "x-aims-auth-token: ${TOKEN}" -X POST https://api.cloudinsight.alertlogic.com/iris/v3/12341ab29e36-394e-11e9-a004-720004270420/complete -d '{"reason_code": "further_action", "notes": "This incident is closed because of y"}'
      requestBody:
        description:  'The value in notes will be displayed in the customer console as the reason for incident closure/completion. The value in reason code is used to classify the reason for closure.'
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                notes:
                  type: string
                  description: Notes about completion
                reason_code:
                  type: string
                  description: Reason for completion
                  enum:
                    - further_action
                    - acceptable_risk
                    - compensating_control
                    - threat_not_valid
                    - not_concluded
                    - other
              required:
                - notes
                - reason_code
            examples:
              Complete incident body:
                value:
                  notes: This incident is because of X
                  reason_code: compensating_control
      parameters:
        - schema:
            type: string
          name: account_id
          in: path
          required: true
          description: AIMS Account ID
        - schema:
            $ref: '#/components/schemas/IncidentId'
          name: incident_id
          in: path
          required: true
  '/iris/v3/{account_id}/{incident_id}/feedback':
    post:
      summary: Add feedback to an incident
      tags:
        - UI operations
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomerFeedback'
              examples:
                Add feedback response example:
                  value:
                    feedback: My feedback
                    feedback_datetime: '2020-05-25T19:21:04.854130+00:00'
                    feedback_reason: further_action
                    feedback_uid: FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF
                    feedback_user: 'User Name <user@email.org>'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Invalid account/incident id:
                  value:
                    error: Invalid AccountId or IncidentId supplied
                    code: 400
                Invalid body:
                  value:
                    error: Request body should be valid JSON
                    code: 400
                Invalid arguments:
                  value:
                    error: Invalid arguments
                    code: 400
        '401':
          description: Unauthorized
        '404':
          description: account_id incident_id combination not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              examples:
                Http 404 example:
                  value:
                    error: "Not found"
                    code: 404
        '500':
          description: Internal Server Error
      operationId: add_feedback
      description: Add feedback to incident
      security:
        - X-AIMS-Auth-Token: []
      x-code-samples:
        - lang: Request Sample
          source: |
            curl -H "x-aims-auth-token: ${TOKEN}" -X POST https://api.cloudinsight.alertlogic.com/iris/v3/1234/1ab29e36-394e-11e9-a004-720004270420/feedback -d '{"customer_feedback": "My feedback", "customer_feedback_reason": "further_action"}'
      requestBody:
        description: 'The value in customer_feedback will be added to the incident and visible in the customer console, the value in customer_feedback_reason is used to classify the type of feedback.'
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customer_feedback:
                  type: string
                  description: Feedback to add to incident
                customer_feedback_reason:
                  type: string
                  description: Reason for feedback
                  enum:
                    - further_action
                    - acceptable_risk
                    - compensating_control
                    - threat_not_valid
                    - not_concluded
                    - other
              required:
                - customer_feedback
                - customer_feedback_reason
            examples:
              Add customer feedback body:
                value:
                  customer_feedback: My feedback
                  customer_feedback_reason: futher_action
      parameters:
        - schema:
            type: string
          name: account_id
          in: path
          required: true
          description: AIMS Account ID
        - schema:
            $ref: '#/components/schemas/IncidentId'
          name: incident_id
          in: path
          required: true
components:
  schemas:
    IncidentId:
      type: string
      description: IRIS incident ID can either be a length 16 alpha-numeric string e.g. e11111ee11111111 or a UUID e.g. XXXX0000-0000-0000-0000-0XXX00000000
    Incident:
      title: Incident
      type: object
      description: IRIS incident
      x-examples:
        Incident Example: null
      properties:
        accountId:
          type: string
          description: AIMS Account Id
        all_assets:
          type: array
          items:
            type: object
        assets:
          type: object
          properties:
            __asset:
              type: object
            __source:
              type: string
            al__deployment:
              type: string
        createTime:
          type: number
          description: Incident creation time
        createtime_str:
          type: string
          description: Incident creation time in ISO format
        customer:
          type: string
          description: Customer name
        customer_status:
          type: object
          properties:
            status:
              type: string
            status_change_time:
              type: string
        desc:
          type: string
        humanFriendlyId:
          type: string
        incident:
          type: object
          properties:
            description:
              type: string
            summary:
              type: string
            threatRating:
              type: string
        incidentId:
          type: string
          description: Incident ID
        incident_attack_class:
          type: string
        incident_class:
          type: string
        incident_type:
          type: string
        snooze_status:
          type: object
          properties:
            period_ms:
              type: number
            reason_code:
              type: string
            snoozed:
              type: boolean
        summary:
          type: string
        updateTime:
          type: number
        updatetime_str:
          type: string
      required:
        - accountId
        - incidentId
        - incident
        - humanFriendlyId
        - desc
        - customer_status
        - createTime
        - createtime_str
        - updateTime
        - updatetime_str
        - customer
    ErrorResponse:
      title: Error response
      type: object
      description: Error response object
      properties:
        error:
          type: string
          description: error message
        code:
          type: number
          description: http error code
    IncidentKey:
      title: IncidentKey
      type: object
      description: Incident key object
      properties:
        incidentId:
          type: string
        humanFriendlyId:
          type: string
        accountId:
          type: string
    FriendlyResponse:
      title: FriendlyResponse
      type: array
      items:
        $ref: '#/components/schemas/IncidentKey'
      description: FriendlyResponse list
      x-examples:
        FriendlyResponse Example: null
      required:
        - response
    AssociatedElaborations:
      title: AssociatedElaborations
      type: object
      description: AssociatedElaborations object
      x-examples:
        AssociatedElaborations Example: null
      properties:
        filter:
          type: object
        returnVals:
          type: array
          items:
            type: object
            description: Values returned by the query
        stats:
          type: object
    IncidentsByTime:
      title: IncidentsByTime
      type: array
      items:
        $ref: '#/components/schemas/Incident'
      description: IncidentsByTime list
    CustomerFeedback:
      title: CustomerFeedback
      type: object
      description: Customer feedback response object
      properties:
        feedback:
          type: string
        feedback_user:
          type: string
        feedback_uid:
          type: string
        feedback_reason:
          type: string
        feedback_datetime:
          type: string
      required:
        - feedback
        - feedback_datetime
        - feedback_reason
        - feedback_uid
        - feedback_user
    CompleteIncident:
      title: Incident completion responses
      type: object
      description: Incident completion response object
      properties:
        new:
          type: object
          properties:
            notes:
              type: string
            reason_code:
              type: string
            status:
              type: string
            status_change_time:
              type: string
          required:
            - notes
            - reason_code
            - status
            - status_change_time
        old:
          type: object
          properties:
            status:
              type: string
            status_change_time:
              type: string
          required:
            - status
            - status_change_time
      required:
        - new
        - old
  securitySchemes:
    X-AIMS-Auth-Token:
      name: X-AIMS-Auth-Token
      type: apiKey
      in: header
      description: AIMS Authentication Token
tags:
  - name: Incident operations
    description: IRIS incident operations
  - name: UI operations
    description: IRIS operations available through the console